# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/examples/ipv6
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-fragmentation-ipv6 "ns3.37-fragmentation-ipv6-default")
set_tests_properties(ctest-fragmentation-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;1;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-two-MTU "ns3.37-fragmentation-ipv6-two-MTU-default")
set_tests_properties(ctest-fragmentation-ipv6-two-MTU PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;10;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-icmpv6-redirect "ns3.37-icmpv6-redirect-default")
set_tests_properties(ctest-icmpv6-redirect PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;19;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-loose-routing-ipv6 "ns3.37-loose-routing-ipv6-default")
set_tests_properties(ctest-loose-routing-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;28;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-ping6 "ns3.37-ping6-default")
set_tests_properties(ctest-ping6 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;37;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd "ns3.37-radvd-default")
set_tests_properties(ctest-radvd PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;46;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-two-prefix "ns3.37-radvd-two-prefix-default")
set_tests_properties(ctest-radvd-two-prefix PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;55;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-test-ipv6 "ns3.37-test-ipv6-default")
set_tests_properties(ctest-test-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;64;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-wsn-ping6 "ns3.37-wsn-ping6-default")
set_tests_properties(ctest-wsn-ping6 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;71;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-PMTU "ns3.37-fragmentation-ipv6-PMTU-default")
set_tests_properties(ctest-fragmentation-ipv6-PMTU PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;82;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/ipv6/CMakeLists.txt;0;")
