# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/scratch
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_scratch-simulator "ns3.37-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_tcp-many-clients-single-server "ns3.37-tcp-many-clients-single-server-default")
set_tests_properties(ctest-scratch_tcp-many-clients-single-server PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_tcp-single-client-server "ns3.37-tcp-single-client-server-default")
set_tests_properties(ctest-scratch_tcp-single-client-server PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_two-LANs "ns3.37-two-LANs-default")
set_tests_properties(ctest-scratch_two-LANs PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/scratch/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;59;create_scratch;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.37-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;47;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;89;create_scratch;/home/george/workspace/ns-allinone-3.37/ns-3.37/scratch/CMakeLists.txt;0;")
