# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/src/propagation/examples
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/src/propagation/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-propagation-loss "ns3.37-main-propagation-loss-default")
set_tests_properties(ctest-main-propagation-loss PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/propagation/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/propagation/examples/CMakeLists.txt;1;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/propagation/examples/CMakeLists.txt;0;")
add_test(ctest-jakes-propagation-model-example "ns3.37-jakes-propagation-model-example-default")
set_tests_properties(ctest-jakes-propagation-model-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/propagation/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/propagation/examples/CMakeLists.txt;13;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/propagation/examples/CMakeLists.txt;0;")
