# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/src/mobility/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bonnmotion-ns2-example "ns3.37-bonnmotion-ns2-example-default")
set_tests_properties(ctest-bonnmotion-ns2-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-topology "ns3.37-main-random-topology-default")
set_tests_properties(ctest-main-random-topology PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-walk "ns3.37-main-random-walk-default")
set_tests_properties(ctest-main-random-walk PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-ns2-mobility-trace "ns3.37-ns2-mobility-trace-default")
set_tests_properties(ctest-ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-grid-topology "ns3.37-main-grid-topology-default")
set_tests_properties(ctest-main-grid-topology PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;19;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-trace-example "ns3.37-mobility-trace-example-default")
set_tests_properties(ctest-mobility-trace-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;28;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-reference-point-group-mobility-example "ns3.37-reference-point-group-mobility-example-default")
set_tests_properties(ctest-reference-point-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;37;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/mobility/examples/CMakeLists.txt;0;")
