# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.37-example-sixlowpan-default")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.37-example-ping-lr-wpan-default")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.37-example-ping-lr-wpan-beacon-default")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.37-example-ping-lr-wpan-mesh-under-default")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/sixlowpan/examples/CMakeLists.txt;0;")
