# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/src/wimax/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wimax-ipv4 "ns3.37-wimax-ipv4-default")
set_tests_properties(ctest-wimax-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;1;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-multicast "ns3.37-wimax-multicast-default")
set_tests_properties(ctest-wimax-multicast PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;12;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-simple "ns3.37-wimax-simple-default")
set_tests_properties(ctest-wimax-simple PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;388;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;22;build_lib_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/src/wimax/examples/CMakeLists.txt;0;")
