# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/examples/tcp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tcp-large-transfer "ns3.37-tcp-large-transfer-default")
set_tests_properties(ctest-tcp-large-transfer PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;1;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-star-server "ns3.37-tcp-star-server-default")
set_tests_properties(ctest-tcp-star-server PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;10;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-star "ns3.37-star-default")
set_tests_properties(ctest-star PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;19;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bbr-example "ns3.37-tcp-bbr-example-default")
set_tests_properties(ctest-tcp-bbr-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;30;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bulk-send "ns3.37-tcp-bulk-send-default")
set_tests_properties(ctest-tcp-bulk-send PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;43;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pcap-nanosec-example "ns3.37-tcp-pcap-nanosec-example-default")
set_tests_properties(ctest-tcp-pcap-nanosec-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;52;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-variants-comparison "ns3.37-tcp-variants-comparison-default")
set_tests_properties(ctest-tcp-variants-comparison PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;61;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pacing "ns3.37-tcp-pacing-default")
set_tests_properties(ctest-tcp-pacing PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;71;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-linux-reno "ns3.37-tcp-linux-reno-default")
set_tests_properties(ctest-tcp-linux-reno PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;81;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-validation "ns3.37-tcp-validation-default")
set_tests_properties(ctest-tcp-validation PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;92;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-dctcp-example "ns3.37-dctcp-example-default")
set_tests_properties(ctest-dctcp-example PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1618;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;104;build_example;/home/george/workspace/ns-allinone-3.37/ns-3.37/examples/tcp/CMakeLists.txt;0;")
