# CMake generated Testfile for 
# Source directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/utils
# Build directory: /home/george/workspace/ns-allinone-3.37/ns-3.37/cmake-cache/utils
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-test-runner "ns3.37-test-runner-default")
set_tests_properties(ctest-test-runner PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/utils/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;30;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;0;")
add_test(ctest-bench-scheduler "ns3.37-bench-scheduler-default")
set_tests_properties(ctest-bench-scheduler PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/utils/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;37;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;0;")
add_test(ctest-bench-packets "ns3.37-bench-packets-default")
set_tests_properties(ctest-bench-packets PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/utils/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;45;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;0;")
add_test(ctest-print-introspected-doxygen "ns3.37-print-introspected-doxygen-default")
set_tests_properties(ctest-print-introspected-doxygen PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/utils/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;52;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;0;")
add_test(ctest-perf-io "ns3.37-perf-io-default")
set_tests_properties(ctest-perf-io PROPERTIES  WORKING_DIRECTORY "/home/george/workspace/ns-allinone-3.37/ns-3.37/build/utils/perf/" _BACKTRACE_TRIPLES "/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1411;add_test;/home/george/workspace/ns-allinone-3.37/ns-3.37/build-support/macros-and-definitions.cmake;1465;set_runtime_outputdirectory;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;61;build_exec;/home/george/workspace/ns-allinone-3.37/ns-3.37/utils/CMakeLists.txt;0;")
